name: Group Scheduler Frontend Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --platform linux/arm64 --push --tag ${{ secrets.DOCKER_USERNAME }}/group-scheduler-frontend:latest .